### ISSUE TITLE
Replace MRAN with RSPM

### ISSUE THREAD

**Issue by dinakar29** [insightsengineering/r-license-report#5]
Use RSPM snapshots instead of MRAN

**Comment by arkadiuszbeer** [comment]
Consider adding `DEFAULT_RSPM` sys. variable as base URL to RSPM ?

**Comment by dinakar29** [comment]
Would be better to add this as an input to the Action here: https://github.com/insightsengineering/r-license-report/blob/main/action.yaml#L18-L21 and also to the `optparse` CLI options.
